Trigger action
artipie/central pull request #18
Opened 2021-06-24 13:16 UTC by genryxy

Part of #14

2021-06-28 07:19 UTC, genryxy commented
@g4s8 could you please check again. It tried to retype dash according to [this](https://stackoverflow.com/questions/66321206/error-docker-context-create-requires-exactly-1-argument)

2021-09-09 08:22 UTC, g4s8 commented on .github/workflows/deploy.yml
> +          docker-compose build --build-arg https_proxy=http://localhost:3128
@genryxy no-no, just use step environment to setup proxy config:
```yaml
- name: Deploy to server
  env:
    http_proxy=http://localhost:3128
  run: |
    your command...
```

2021-09-16 07:43 UTC, genryxy commented
@g4s8 could you please take a look. It started to work now

2021-09-20 08:32 UTC, g4s8 commented
@genryxy could you please edit PR description according to our contribution guid: https://github.com/artipie/artipie/blob/master/CONTRIBUTING.md#pull-request-style

2021-09-20 08:37 UTC, genryxy commented
@g4s8 edited description and title

2021-09-20 08:37 UTC, g4s8 requested changes
@genryxy please check my comments

2021-09-20 08:37 UTC, g4s8 commented on .github/workflows/deploy.yml
> +          rsync -r /home/runner/myw/_work/central/central/* ${{ secrets.REMOTE_HOST }}:${{ secrets.REMOTE_TARGET }} -v
Absolute path here is not a good idea: we can change runner or restart it from another directory, and it'll break the script. You can use relative path (relative to repository location) or use `GITHUB_WORKSPACE` environment, see: https://docs.github.com/en/actions/reference/environment-variables#default-environment-variables

2021-09-20 08:37 UTC, g4s8 commented on .github/workflows/deploy.yml
> +          echo "----- rsync passed successfully -----"
No need to put debugging message here. If you want verbose output, just enable `-v` flag for `rsync` command.

2021-09-20 08:37 UTC, g4s8 commented on .github/workflows/deploy.yml
> +          echo "----- successfully finished script -----"
Same here.

2021-09-20 08:56 UTC, genryxy commented
@g4s8 thanks, corrected

2021-09-20 09:56 UTC, g4s8 approved these changes
@genryxy thanks

2021-09-20 09:56 UTC, merged